# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.3.4

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
      with:
        # Set always-auth in npmrc
        always-auth: true
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
        node-version: 16.12.0

      - name: Prepare git
        run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install from Cache
        if: steps.cache-node-modules.outputs.cache-hit == 'true'
        run: npm install

      - name: Install from Web
        if: steps.cache-node-modules.outputs.cache-hit == 'false'
        run: npm ci

    # Runs a set of commands using the runners shell
    - name: Build
      run: npm run build:ci

    - name: Create pdf
      run: |
        npm run pdf-sequence:ci
        cp *.pdf ./public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
